version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
  pre_build:
    commands:
    - echo "Installing NPM dependencies"
    - npm install
  build:
    commands:
    - echo "Running Cypress tests"
    - npm run cy:parallel || echo "Cypress tests failed"
  post_build:
    commands:
    - aws s3 sync allure-report s3://reporte-de-pruebas1/
    - aws s3 --recursive --acl public-read s3://reporte-de-pruebas1/ s3://reporte-de-pruebas1/ --metadata-directive REPLACE