version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
  pre_build:
    commands:
    - echo "Installing NPM dependencies"
    - npm install
  build:
    commands:
    - echo "Running Cypress tests"
    - npm run cy:parallel || echo "Cypress tests failed"